friend-list/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/index'
  get 'home/about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

friend-list/app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

friend-list/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

friend-list/app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.where(user_id: current_user.id)
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: 'Friend was successfully created.' }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1
  # PATCH/PUT /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: 'Friend was successfully updated.' }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: 'Friend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

friend-list/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

friend-list/app/helpers/friends_helper.rb
module FriendsHelper
end

friend-list/app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Nme" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-dark"%>
  </div>
<% end %>

friend-list/app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Show', @friend, class: "btn btn-dark" %>
<%= link_to 'Back', friends_path, class: "btn btn-dark" %>

friend-list/app/views/friends/index.html.erb
<h1>Friends</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">User Id</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= friend.user_id %></td>
        <td><%= link_to 'Show', friend %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class: "btn btn-dark" %>

friend-list/app/views/friends/new.html.erb
<h1>New Friend</h1>
<br>
<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path, class: "btn btn-dark" %>

friend-list/app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>
<div class="jumbotron">
  <p>
    <strong>First name:</strong>
    <%= @friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= @friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= @friend.twitter %>
  </p>
  <br>
  <hr class="my-4">
  <%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-dark" %>
  <%= link_to 'Back', friends_path, class: "btn btn-dark" %>
</div>

friend-list/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend-List App', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Friends', friends_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Add new friend', new_friend_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'About Us', home_about_path, class: 'nav-link' %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

friend-list/app/views/home/about.html.erb
abot us

friend-list/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>