blog/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles, only: %i[index show new create edit update destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

blog/app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  belongs_to :user
end

blog/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 50 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  has_many :articles, dependent: :destroy

  has_secure_password
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform that action.'
      redirect_to login_path
    end
  end

  def require_article_author
    unless current_user == @article.user || current_user.admin?
      flash[:alert] = 'You can only edit or delete your own articles.'
      redirect_to @article
    end
  end

  def require_same_user
    unless current_user == @user
      flash[:alert] = 'You can only edit your own account.'
      redirect_to @user
    end
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_article_author, only: %i[edit update destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end
end

blog/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in successfully.'
      redirect_to user
    else
      flash[:alert] = 'Email or password is incorrect.'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out.'
    redirect_to root_path
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update]

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def show
    @articles = @user.articles
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(params.require(:user).permit(:username, :email, :password))
      flash[:notice] = 'Account updated!'
      redirect_to @user, notice: 'Account information was successfully updated.'
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(params.require(:user).permit(:username, :email, :password))
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_index_path, notice: 'User was successfully created.'
    else
      render 'new'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 100 })
    email_address = user.email
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded mx-auto d-block mb-5')
  end
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/views/articles/_article.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="row">
      <div class="col-12">
        <div class="card text-center shadow-sm rounded">
          <div class="card-header">
            <i>by <%= link_to article.user.username, user_path(article.user) %></i>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'Show', article_path(article.id), class: "btn btn-primary" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to 'Update', edit_article_path(article), class: "btn btn-primary" %>
              <%= link_to 'Delete', article_path(article.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            Last updated: <%= time_ago_in_words(article.updated_at) %> ago
          </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
</div>

blog/app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>

  <%= render 'shared/errors', obj: @article %>

  <div class="form-group row">
    <%= form.label :title, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

blog/app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>
<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-4">
  <div class="page_info">
    <%= page_entries_info @articles %>
  </div>
  <%= will_paginate @articles, :container => false %>
</div>

<p>
  <%= link_to 'Create new article', new_article_path, class: "btn btn-primary" %>
</p>

blog/app/views/articles/new.html.erb
<h1 class="text-center mt-4">New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<h1 class="text-center mt-4"><%= @article.title %></h1>
<div class="container">
    <div class="row">
      <div class="col-12">
        <div class="card text-center shadow-sm rounded">
          <div class="card-header">
            <i>by <%= @article.user.username %></i>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to 'Update', edit_article_path(@article), class: "btn btn-primary" %>
              <%= link_to 'Delete', article_path(@article.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            Last updated: <%= time_ago_in_words(@article.updated_at) %> ago
          </div>
        </div>
      </div>
    </div>
    <br>
</div>

blog/app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; Blog App</small>
  </div>
</footer>

blog/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Blog', home_index_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', home_index_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Articles', articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Bloggers', users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

blog/app/views/layouts/_messages.html.erb
<% if flash.any? %>
  <% flash.each do |name, msg| %>
    <div class="alert <%="alert-#{name == 'notice'? 'success' : 'danger'}"%> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

blog/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>Blog App</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body class="d-flex flex-column">
<%= render 'layouts/header' %>
<div class="container" id="page-content">
  <br>
<%= render 'layouts/messages' %>
  <br>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>

blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

blog/app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <%= render 'shared/errors', obj: @user %>

  <div class="form-group row">
    <%= form.label :username, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.text_field :username, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :email, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.email_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :password, class: "col-2 col-form-label" %>
    <div class="col-10">
      <%= form.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn btn-primary") %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1 class="text-center mt-4">Editing Article</h1>

<%= render 'form' %>

blog/app/views/users/index.html.erb
<div class="container">
  <div class="flickr_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-12">
        <div class="card text-center shadow-sm rounded">
          <div class="card-header">
            <i><%= link_to user.username, user_path(user.id) %></i>
          </div>
          <div class="card-body">
            <%= gravatar_for(user, size: 150) %>
            <p class="card-text"><%= pluralize(user.articles.count, 'article') %></p>
          </div>
          <div class="card-footer text-muted">
            <%= user.email %>
          </div>
        </div>
      </div>
    </div>
    <br>
  <% end %>
  <div class="flickr_pagination mb-4">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate @users, :container => false %>
  </div>
</div>

blog/app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up</h1>

<%= render 'form'%>

blog/app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %></h1>

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card text-center shadow-sm rounded">
        <div class="card-header">

        </div>
        <div class="card-body">
          <%= gravatar_for @user %>
          <div class="card-text"><%= simple_format(@user.email) %></div>
          <% if logged_in? && @user == current_user %>
            <%= link_to 'Update', edit_user_path(@user), class: "btn btn-primary" %>
            <%= link_to 'Delete', users_path(@user.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          Last updated: <%= time_ago_in_words(@user.updated_at) %> ago
        </div>
      </div>
    </div>
  </div>
  <br>
</div>

<%= render 'articles/article' %>